version: "3"
  
services:
  db:
    image: postgres
    restart: unless-stopped
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=123fenix
    volumes:
      - $PWD/postgresql:/var/lib/postgresql
      - $PWD/postgresql_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=123fenix
    volumes:
      - $PWD/sonarqube_conf:/opt/sonarqube/conf
      - $PWD/sonarqube_data:/opt/sonarqube/data
      - $PWD/sonarqube_extensions:/opt/sonarqube/extensions
      - $PWD/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

networks:
  sonarnet:
